language: smalltalk
sudo: false
os:
- linux
smalltalk:
- Pharo64-7.0
- Pharo-7.0
- Pharo-6.1
- Pharo-6.0
- Pharo-5.0
matrix:
  allow_failures:
  - smalltalk: Pharo64-7.0
  - smalltalk: Pharo-7.0
  fast_finish: true
before_deploy:
  - cp "${SMALLTALK_CI_IMAGE}" "RenoirSt.image"
  - cp "${SMALLTALK_CI_CHANGES}" "RenoirSt.changes"
  - zip -q "${TRAVIS_BRANCH}-${TRAVIS_SMALLTALK_VERSION}.zip" "RenoirSt.image" "RenoirSt.changes"
deploy:
  provider: releases
  api_key:
    secure: WlrpuZMaqzwXy5Yc2HmX2y11q7f0FwE+seqrwjaOvfT/5+dNR/9pQt2+fLQsEM66UtZ3ycanCdh1Ma0nw5XbAVCAHbFihWkFoIXaoBFPxso30y80Ku2RouGlvEkGxMgeI6DX7r68pblzq6XeP9GdAF83xXnF0X8w0JW38q1IY8mUPonIvUZ7heJOoBKmcYWuxC8KmqywHKqDFkyeZYVHmfyObkX+mvqfV9Aty7gnAlbtrF1Ks0g8glVK6BnEv5fTAs2bbp4biX+M1vs+UwTU+vfJxgGUugvqDuODwT2AjoXr1mAAOWlOyRptpCXYD0RKmTAA82jcHJrN9H/42QNjNHPt4a22fr2cfxD7GATFYl3ZnIdx1ayym7Xsk+wjRtfXOrufwO1MeZymDMPmWZO4TctIjtrcKHcQ/lDm2RiA6eFQ2Y13SxTZFxNdmRiXoJ2DUlceBsBi6EU35S6Z6G8E74JbvrOhP06xwdfuVDsDCAQP5/J18gQ96mg1jwNdDdH6E++T0yhGNOtQX4V6B/fFoKgI5mPrv1Wxm3oJ9NQbem1YgGITK3TJmlfGAORVQb6n74PdERgJgwSPZDepBXLHaGJbPdWyVPeTRMjhgsBW5O8KeYfEUQi5+EQm9EljNPK16hTVFLWN4KmAGOg7ofDof4KSRVtmMv57bIJRUFVw/+g=
  file: "${TRAVIS_BRANCH}-${TRAVIS_SMALLTALK_VERSION}.zip"
  skip_cleanup: true
  on:
    repo: ba-st/RenoirSt
    tags: true
